training:
  batch_size: 8
  num_air_features: 3 # humidity, temperature...
  num_meteo_features: 2
  
  outseq_len: 24
  src_len: 11 # số trạm đã biết
  
  hidden_size: 16
  num_extractor_layers: 1
  gcn_dim: 32
  dropout: 0.2

  optim:
    lr: 0.001
    optimizer: "adam"
    sgd:
      momentum: 0.9
      weight_decay: 0.001
    adam:
      weight_decay: 0.001
    scheduler: "plateau"
    steplr:
      step_size: 20
    plateau:
      patience: 2
      eps: 0.0000001 # 1e-7
      monitor: "mae"


data:
  normalize_mean:
    temperature: 27.133
    humidity: 79.378
    PM2.5: 48.219
    wind_speed: 2.332
    surface_pressure: 96957.127
  normalize_std:
    temperature: 6.098
    humidity: 16.169
    PM2.5: 55.535
    wind_speed: 1.9
    surface_pressure: 4101.496