training:
  batch_size: 8
  epochs: 10

  n_features: 11 # bejing is 11 else 3
  num_stations: 12 # bejing is 12 else 11
  input_embedding_dim: 64
  loc_embedding_dim: 12
  time_embedding_dim: 8
  num_enc_gnn_layers: 2
  num_dec_gnn_layers: 2
  num_attn_heads: 1 # should divisible by n_features + 4 * time_embedding_dim
  attn_feedforward_dim: 64
  edge_dim: 12
  gnn_dim: 32
  num_groups: 3
  inseq_len: 168
  outseq_len: 24
  dropout: 0.2

  optim:
    lr: 0.0005
    optimizer: "adam"
    sgd:
      momentum: 0.9
      weight_decay: 0.7
    adam:
      weight_decay: 0.1
    scheduler: "plateau"
    steplr:
      step_size: 10
    plateau:
      patience: 5
      eps: 0.0000001 # 1e-7
      monitor: "mae"

data:
  # normalize_mean:
  #   temperature: 8.8
  #   humidity: 9.05
  #   PM2.5: 0.55
  # normalize_std:
  #   temperature: 37.11
  #   humidity: 90.95
  #   PM2.5: 269.45

  normalize_mean:
    temperature: 26.55
    humidity: 75.77
    PM2.5: 45.06
  normalize_std:
    temperature: 5.94
    humidity: 15.43
    PM2.5: 42.23