training:
  batch_size: 8
  epochs: 10

  n_features: 3
  pos_embedding_dim: 32
  gcn_dim: 29
  gcn_hidden_dim: 64
  expansion_factor: 3
  num_attn_heads: 8
  inseq_len: 168
  outseq_len: 24
  dropout: 0.2

  optim:
    lr: 0.001
    optimizer: "adam"
    sgd:
      momentum: 0.9
      weight_decay: 0.001
    adam:
      weight_decay: 0.001
    scheduler: "steplr"
    steplr:
      step_size: 20
    plateau:
      patience: 5
      eps: 0.0000001 # 1e-7
      monitor: "mae"

data:
  # normalize_mean:
  #   temperature: 8.8
  #   humidity: 9.05
  #   PM2.5: 0.55
  # normalize_std:
  #   temperature: 37.11
  #   humidity: 90.95
  #   PM2.5: 269.45

  normalize_mean:
    temperature: 26.55
    humidity: 75.77
    PM2.5: 45.06
  normalize_std:
    temperature: 5.94
    humidity: 15.43
    PM2.5: 42.23