training:
  batch_size: 32
  n_features: 3 # humidity, temperature and pm2.5
  n_sequence: 168 # chiều dài timesteps đầu vào
  output_dim: 24 # chiều dài dự đoán
  src_len: 11 # số trạm đã biết tối đa
  num_enc_layers: 1 # số encoder layer của LSTMAutoEncoder
  num_dec_layers: 1 # số decoder layer của LSTMAutoEncoder
  hidden_size_autoencoder: 128 # hidden_size của LSTMAutoEncoder
  num_extractor_layers: 2
  extractor_size: 64
  attn_dropout: 0.2
  max_num_mask: 3
  optim:
    lr: 0.001
    scheduler: "plateau"
    steplr:
      step_size: 50
    plateau:
      patience: 5
      eps: 0.0000001 # 1e-7
      monitor: "mdape"


data:
  normalize_mean:
    temperature: 26.546403688351234
    humidity: 75.76537114905305
    PM2.5: 45.063545172080076
  normalize_std:
    temperature: 5.938755783975602
    humidity: 15.434225331097021
    PM2.5: 42.227863829824535