training:
  batch_size: 32
  
  n_stations: 11
  n_features: 7
  seq_len: 168

  dropout: 0.3
  # Convolution Extractor Config
  channels1: 64
  kernel_size1: 5
  channels2: 32
  kernel_size2: 3
  channels3: 16
  kernel_size3: 1

  extractor_size: 128

  # Spatial Temporal Config
  lstm_hidden_size: 128
  lstm_num_layers: 3
  lstm_lookup_size: 2
  lstm_output_size: 512
  
  # Inverse Distance Config
  ff_size: 32
  idw_beta: 2.0

  fusion_size: 64
  output_size: 24

  optim:
    lr: 0.0001
    optimizer: "sgd"
    sgd:
      momentum: 0.8
      weight_decay: 0.9
    adam:
      weight_decay: 0.9
    scheduler: "plateau"
    steplr:
      step_size: 20
    plateau:
      patience: 4
      eps: 0.0000001 # 1e-7
      monitor: "mdape"

data:
  normalize_mean:
    temperature: 26.55
    humidity: 75.77
    PM2.5: 45.06
  normalize_std:
    temperature: 5.94
    humidity: 15.43
    PM2.5: 42.23

  # normalize_mean:
  #   temperature: 8.8
  #   humidity: 9.05
  #   PM2.5: 0.55
  # normalize_std:
  #   temperature: 37.11
  #   humidity: 90.95
  #   PM2.5: 269.45